import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import { fetchPokemon } from '@/api/fetchPokemon';

import ArrowIcon from '../assets/icons/arrow.svg';

// Move the function outside the component
const changeLanguage = (router: any, locale: string) => {
  router.push(router.pathname, router.asPath, { locale });
};

export default function Home() {
  const router = useRouter();
  const { t } = useTranslation('common');

  useEffect(() => {
    const fetchPokemonBerry = async () => {
      const res = await fetchPokemon({
        name: 'oran',
      });
      return res;
    };
    const res = fetchPokemonBerry();
    console.log('pokemon berry', res);
  }, []);

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex h-full flex-col items-center justify-center gap-5'>
        <div className='leading-[var(--line-height-body-bold-l)] font-[var(--font-weight-body-bold-l)] text-[var(--font-size-body-bold-l)]'>
          {t('title')}
        </div>
        <div className='leading-[var(--line-height-body-regular-l)] font-[var(--font-weight-body-regular-l)] text-[var(--font-size-body-regular-l)]'>
          {t('description')}
        </div>
        <div className='flex gap-2.5'>
          <button
            className='h-[52px] cursor-pointer rounded-[30px] border-none bg-[var(--color-red-dark)] px-5 py-2.5 leading-[var(--line-height-body-regular-l)] font-[var(--font-weight-body-regular-l)] text-[var(--color-white)]'
            onClick={() => changeLanguage(router, 'zh-TW')}
          >
            中文
          </button>
          <button
            className='h-[52px] cursor-pointer rounded-[30px] border-none bg-[var(--color-red-dark)] px-5 py-2.5 leading-[var(--line-height-body-regular-l)] font-[var(--font-weight-body-regular-l)] text-[var(--color-white)]'
            onClick={() => changeLanguage(router, 'en')}
          >
            English
          </button>
        </div>
        <div className='flex items-center gap-2.5'>
          <span className='leading-[var(--line-height-body-regular-l)] text-[var(--font-size-body-regular-l)]'>
            icon-sample
          </span>
          <ArrowIcon width={20} height={20} color='green' />
        </div>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'zh', ['common'])),
    },
  };
};
